# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d0137bea73a9e410fe762e3e7ef9b922d8928a75fac494829590f4ede20e8806dc35d1ec2acf41a2fef3bf94ef262a7e32fb9a21c2faec908df221a1fe0d68a

test:
  secret_key_base: 507982796202a907a9271e90a4e776cae9c13017bffe7dfeabaf213397b06c2505a8d7c35ef47e489164286ecee56a6bbc28a417e68959cbe6938152000b34cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
